
import java.awt.Color;
import javax.swing.border.LineBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class booked extends javax.swing.JFrame {

    /**
     * Creates new form booked
     */
    public booked() {
        initComponents();
        gif.setBackground(new Color(0,0,0,0));
        this.setLocationRelativeTo(null);
        this.setOpacity(0.9f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gif = new javax.swing.JPanel();
        thank_you = new javax.swing.JLabel();
        SKIP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        gif.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gif.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        thank_you.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        thank_you.setForeground(new java.awt.Color(255, 51, 102));
        thank_you.setLabelFor(thank_you);
        thank_you.setText("YOUR RIDE IS ON HIS WAY!!!!!.....");
        thank_you.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gif.add(thank_you, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 450, 40));

        SKIP.setBackground(new java.awt.Color(43, 7, 78));
        SKIP.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        SKIP.setForeground(new java.awt.Color(255, 255, 255));
        SKIP.setText("  S K I P");
        SKIP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SKIPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SKIPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SKIPMouseExited(evt);
            }
        });
        gif.add(SKIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, 80, 30));
        SKIP.getAccessibleContext().setAccessibleDescription("[64,11,117]");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg12thproject/H7d1_1.gif"))); // NOI18N
        gif.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SKIPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SKIPMouseClicked
       this.setVisible(false);
       new Billing_rent().setVisible(true);
          
    }//GEN-LAST:event_SKIPMouseClicked

    private void SKIPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SKIPMouseEntered
        // TODO add your handling code here:
        SKIP.setForeground(Color.WHITE);
       SKIP.setBackground(new Color(64,11,117));
       SKIP.setBorder(new LineBorder(new Color(255,255,255) , 1 ,true));
    }//GEN-LAST:event_SKIPMouseEntered

    private void SKIPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SKIPMouseExited
        // TODO add your handling code here:
         SKIP.setForeground(new Color(255,255,255));
       SKIP.setBackground(Color.BLACK);
       SKIP.setBorder(new LineBorder(new Color(43,7,78) , 1 ,true));
    }//GEN-LAST:event_SKIPMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booked().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SKIP;
    private javax.swing.JPanel gif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel thank_you;
    // End of variables declaration//GEN-END:variables
}
