
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Amar
 */
public class Car_reg extends javax.swing.JFrame {

    /**
     * Creates new form Car_reg
     */
    public Car_reg() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setOpacity(0.9f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        carpanel = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TextPanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        model = new javax.swing.JLabel();
        carno = new javax.swing.JLabel();
        yearB = new javax.swing.JLabel();
        YB = new com.toedter.calendar.JDateChooser();
        Licence = new javax.swing.JPanel();
        comp = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        issue = new javax.swing.JLabel();
        ID = new com.toedter.calendar.JDateChooser();
        validity = new javax.swing.JLabel();
        VAL = new com.toedter.calendar.JDateChooser();
        dob = new javax.swing.JLabel();
        DOB = new com.toedter.calendar.JDateChooser();
        licenceno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address_1 = new javax.swing.JTextArea();
        gen = new javax.swing.JLabel();
        optm = new javax.swing.JRadioButton();
        optf = new javax.swing.JRadioButton();
        txtcomp = new javax.swing.JTextField();
        txtl = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        Clear = new javax.swing.JButton();
        Sumit = new javax.swing.JButton();
        txtn = new javax.swing.JTextField();
        txtc = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        cmdclass = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtcode = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        carpanel.setBackground(new java.awt.Color(255, 255, 255));

        icon.setBackground(new java.awt.Color(0,0,0,3));
        icon.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clipboard (4).png"))); // NOI18N
        icon.setText("CAR  REGISTRATION ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout carpanelLayout = new javax.swing.GroupLayout(carpanel);
        carpanel.setLayout(carpanelLayout);
        carpanelLayout.setHorizontalGroup(
            carpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carpanelLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        carpanelLayout.setVerticalGroup(
            carpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
            .addGroup(carpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TextPanel.setBackground(new java.awt.Color(255, 255, 255));

        name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        name.setText("Name");

        model.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        model.setText("Classification");

        carno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        carno.setText("Car Number");

        yearB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        yearB.setText("Year Bought");

        YB.setBackground(new java.awt.Color(255, 255, 255));
        YB.setDateFormatString("yyyy-MM-dd");

        Licence.setBackground(new java.awt.Color(255, 255, 255));
        Licence.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Driving Licence", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24))); // NOI18N

        comp.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        comp.setText("Company of the car ");

        address.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        address.setText("Address");

        issue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        issue.setText("Issue Date");

        ID.setBackground(new java.awt.Color(255, 255, 255));
        ID.setDateFormatString("yyyy-MM-dd");

        validity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        validity.setText("Validity");

        VAL.setBackground(new java.awt.Color(255, 255, 255));
        VAL.setDateFormatString("yyyy-MM-dd");

        dob.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dob.setText("Date of Birth");

        DOB.setBackground(new java.awt.Color(255, 255, 255));
        DOB.setDateFormatString("yyyy-MM-dd");

        licenceno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        licenceno.setText("Licence Number");

        address_1.setColumns(20);
        address_1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        address_1.setRows(5);
        jScrollPane1.setViewportView(address_1);

        gen.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        gen.setText("Gender");

        optm.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(optm);
        optm.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        optm.setText("Male");

        optf.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(optf);
        optf.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        optf.setText("Female");

        txtcomp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtcomp.setBorder(null);

        txtl.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtl.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout LicenceLayout = new javax.swing.GroupLayout(Licence);
        Licence.setLayout(LicenceLayout);
        LicenceLayout.setHorizontalGroup(
            LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LicenceLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LicenceLayout.createSequentialGroup()
                        .addComponent(address)
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 30, Short.MAX_VALUE)
                        .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dob)
                            .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(licenceno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(validity)))
                    .addGroup(LicenceLayout.createSequentialGroup()
                        .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issue)
                            .addComponent(comp))
                        .addGap(50, 50, 50)
                        .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtcomp)
                            .addComponent(jSeparator4))))
                .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(LicenceLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(optm, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(optf)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LicenceLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VAL, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))))
        );
        LicenceLayout.setVerticalGroup(
            LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LicenceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LicenceLayout.createSequentialGroup()
                        .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comp)
                            .addComponent(validity)
                            .addComponent(txtcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VAL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(LicenceLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(issue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(LicenceLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(DOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(dob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(address))
                    .addGroup(LicenceLayout.createSequentialGroup()
                        .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(licenceno)
                            .addComponent(txtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gen)
                            .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(optm)
                                .addComponent(optf))))))
        );

        Clear.setBackground(new java.awt.Color(255, 255, 255));
        Clear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Clear.setText("C l e a r");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Sumit.setBackground(new java.awt.Color(255, 255, 255));
        Sumit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Sumit.setText("S u b m i t");
        Sumit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumitActionPerformed(evt);
            }
        });

        txtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtn.setBorder(null);

        txtc.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtc.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1.setText("C a n c e l");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmdclass.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cmdclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "Suv" }));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Car Code");

        txtcode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtcode.setToolTipText("eg. acb1@#");
        txtcode.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout TextPanelLayout = new javax.swing.GroupLayout(TextPanel);
        TextPanel.setLayout(TextPanelLayout);
        TextPanelLayout.setHorizontalGroup(
            TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(Clear)
                .addGap(155, 155, 155)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(Sumit)
                .addGap(159, 159, 159))
            .addGroup(TextPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TextPanelLayout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextPanelLayout.createSequentialGroup()
                        .addComponent(model)
                        .addGap(56, 56, 56)))
                .addGroup(TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(txtn)
                    .addComponent(cmdclass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearB)
                    .addComponent(carno))
                .addGap(96, 96, 96)
                .addGroup(TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3)
                    .addComponent(YB, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(txtc))
                .addGap(97, 97, 97))
            .addGroup(TextPanelLayout.createSequentialGroup()
                .addGroup(TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TextPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Licence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TextPanelLayout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel2)
                        .addGap(58, 58, 58)
                        .addGroup(TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(txtcode, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TextPanelLayout.setVerticalGroup(
            TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(name)
                        .addComponent(yearB)
                        .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(YB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(model)
                    .addComponent(carno)
                    .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Licence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sumit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(carpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SumitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumitActionPerformed
       
        
        String nm ;
        String mo ;
        String carn ;
        String comp ;
        String ln ;
        String gen;
        String add;
        String st;
        st="Available";
        int I = 0;
        int i = I++;
        
        
        nm = txtn.getText();
       String cl = cmdclass.getSelectedItem().toString();
       String code = txtcode.getText();
        
        carn = txtc.getText();
        comp = txtcomp.getText();
        ln= txtl.getText();
        add = address_1.getText();
        String yb = ((JTextField)YB.getDateEditor().getUiComponent()).getText();
        String id = ((JTextField)ID.getDateEditor().getUiComponent()).getText();
        String va = ((JTextField)VAL.getDateEditor().getUiComponent()).getText();
        String dob = ((JTextField)DOB.getDateEditor().getUiComponent()).getText();
        
                
        if(optm.isSelected())
        gen= "Male";
        else if(optf.isSelected())
        gen= "Female";
        else
        gen = "_";
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/car_bookings","root","mysql");
            Statement stmt = con.createStatement();
            String sq2 = ("insert into car_reg values('"+i+"','"+nm+"','"+cl+"','"+carn+"','"+yb+"','"+add+"','"+gen+"','"+ln+"','"+comp+"','"+id+"','"+va+"','"+dob+"','"+st+"','"+code+"');");
            String sq3 = ("insert into car_details values('"+i+"','"+nm+"','"+gen+"','"+cl+"','"+carn+"','"+ln+"','"+dob+"','"+code+"');");
            stmt.executeUpdate(sq2);
            stmt.executeUpdate(sq3);
            
            if (txtn.equals("") ||  txtc.equals("") || txtc.equals("")  || txtcomp.equals("") || txtl.equals("") || address_1.equals("") || YB.equals("") || ID.equals("") || VAL.equals("")||  DOB.equals(""))
            {
                JOptionPane.showMessageDialog(null, "empty fields");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Succesfully added");
                this.setVisible(false);
                new login().setVisible(true);
            }

            } catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

            }
        
        
    }//GEN-LAST:event_SumitActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
             
             txtn.setText("");
             
             txtc.setText("");
             txtcomp.setText("");
             txtl.setText("");
             address_1.setText("");

    }//GEN-LAST:event_ClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
        this.setVisible(false);
        new create_acc().setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Car_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Car_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Car_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Car_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Car_reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private com.toedter.calendar.JDateChooser DOB;
    private com.toedter.calendar.JDateChooser ID;
    private javax.swing.JPanel Licence;
    private javax.swing.JButton Sumit;
    private javax.swing.JPanel TextPanel;
    private com.toedter.calendar.JDateChooser VAL;
    private com.toedter.calendar.JDateChooser YB;
    private javax.swing.JLabel address;
    private javax.swing.JTextArea address_1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel carno;
    private javax.swing.JPanel carpanel;
    private javax.swing.JComboBox<String> cmdclass;
    private javax.swing.JLabel comp;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel gen;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel issue;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel licenceno;
    private javax.swing.JLabel model;
    private javax.swing.JLabel name;
    private javax.swing.JRadioButton optf;
    private javax.swing.JRadioButton optm;
    private javax.swing.JTextField txtc;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtcomp;
    private javax.swing.JTextField txtl;
    private javax.swing.JTextField txtn;
    private javax.swing.JLabel validity;
    private javax.swing.JLabel yearB;
    // End of variables declaration//GEN-END:variables
}
