
import java.awt.Color;

import java.sql.Connection;
import java.sql.DriverManager;


import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
 



public class create_acc extends javax.swing.JFrame {

    
    public create_acc() {
       initComponents();
       
       this.setLocationRelativeTo(null);
        this.setOpacity(0.9f);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BTMgen = new javax.swing.ButtonGroup();
        jSeparator11 = new javax.swing.JSeparator();
        BTMud = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        F_name = new javax.swing.JLabel();
        L_name = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        PASS = new javax.swing.JLabel();
        RE_pass = new javax.swing.JLabel();
        Pan = new javax.swing.JLabel();
        Invite = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        txtF_name = new javax.swing.JTextField();
        txtL_name = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        password1 = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        txtpan = new javax.swing.JTextField();
        txtinvite = new javax.swing.JTextField();
        txtcar = new javax.swing.JTextField();
        optmale = new javax.swing.JRadioButton();
        optfemale = new javax.swing.JRadioButton();
        cmdcity = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        optu = new javax.swing.JRadioButton();
        optd = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        Cancel = new javax.swing.JPanel();
        CANCEL = new javax.swing.JLabel();
        Clear = new javax.swing.JPanel();
        CLEAR = new javax.swing.JLabel();
        Confirm = new javax.swing.JPanel();
        CONFIRM = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        car = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        reg_car = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(29, 59, 85));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user (14).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(29, 59, 85));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 59, 85), 6, true));
        jPanel3.setForeground(new java.awt.Color(0, 122, 153));

        F_name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        F_name.setForeground(new java.awt.Color(255, 255, 255));
        F_name.setText("F_Name");

        L_name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        L_name.setForeground(new java.awt.Color(255, 255, 255));
        L_name.setText("L_Name");

        Email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email-ID");

        PASS.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        PASS.setForeground(new java.awt.Color(255, 255, 255));
        PASS.setText("Password");

        RE_pass.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        RE_pass.setForeground(new java.awt.Color(255, 255, 255));
        RE_pass.setText("Rewrite Password");

        Pan.setBackground(new java.awt.Color(0, 0, 0));
        Pan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Pan.setForeground(new java.awt.Color(255, 255, 255));
        Pan.setText("PAN");

        Invite.setBackground(new java.awt.Color(0, 0, 0));
        Invite.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Invite.setForeground(java.awt.Color.white);
        Invite.setText("Invite Code");

        City.setBackground(new java.awt.Color(0, 0, 0));
        City.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        City.setForeground(new java.awt.Color(255, 255, 255));
        City.setText("City You'll Drive In");

        Gender.setBackground(new java.awt.Color(0, 0, 0));
        Gender.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Gender.setForeground(java.awt.Color.white);
        Gender.setText("Gender");

        txtF_name.setBackground(new java.awt.Color(29, 59, 85));
        txtF_name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtF_name.setForeground(new java.awt.Color(2, 154, 153));
        txtF_name.setBorder(null);

        txtL_name.setBackground(new java.awt.Color(29, 59, 85));
        txtL_name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtL_name.setForeground(new java.awt.Color(2, 154, 153));
        txtL_name.setBorder(null);

        txtemail.setBackground(new java.awt.Color(29, 59, 85));
        txtemail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtemail.setForeground(new java.awt.Color(2, 154, 153));
        txtemail.setBorder(null);

        password1.setBackground(new java.awt.Color(29, 59, 85));
        password1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        password1.setForeground(new java.awt.Color(2, 154, 153));
        password1.setBorder(null);

        password2.setBackground(new java.awt.Color(29, 59, 85));
        password2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        password2.setForeground(new java.awt.Color(2, 154, 153));
        password2.setBorder(null);
        password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password2ActionPerformed(evt);
            }
        });

        txtpan.setBackground(new java.awt.Color(29, 59, 85));
        txtpan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtpan.setForeground(new java.awt.Color(2, 154, 153));
        txtpan.setBorder(null);

        txtinvite.setBackground(new java.awt.Color(29, 59, 85));
        txtinvite.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtinvite.setForeground(new java.awt.Color(2, 154, 153));
        txtinvite.setBorder(null);
        txtinvite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinviteActionPerformed(evt);
            }
        });

        txtcar.setBackground(new java.awt.Color(29, 59, 85));
        txtcar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtcar.setForeground(new java.awt.Color(2, 154, 153));
        txtcar.setBorder(null);

        optmale.setBackground(new java.awt.Color(29, 59, 85));
        BTMgen.add(optmale);
        optmale.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        optmale.setForeground(new java.awt.Color(255, 255, 255));
        optmale.setText("Male");
        optmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optmaleActionPerformed(evt);
            }
        });

        optfemale.setBackground(new java.awt.Color(29, 59, 85));
        BTMgen.add(optfemale);
        optfemale.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        optfemale.setForeground(new java.awt.Color(255, 255, 255));
        optfemale.setText("Female");
        optfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optfemaleActionPerformed(evt);
            }
        });

        cmdcity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cmdcity.setForeground(new java.awt.Color(2, 154, 153));
        cmdcity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Kolkata", "Bangalore", "Hyderabad", "Chennai", "Ahmedabad", "Pune", " " }));
        cmdcity.setBorder(null);

        jPanel4.setBackground(new java.awt.Color(29, 59, 85));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 154, 153), 3, true));

        optu.setBackground(new java.awt.Color(29, 59, 85));
        BTMud.add(optu);
        optu.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        optu.setForeground(new java.awt.Color(255, 255, 255));
        optu.setText("User");
        optu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optuActionPerformed(evt);
            }
        });

        optd.setBackground(new java.awt.Color(29, 59, 85));
        BTMud.add(optd);
        optd.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        optd.setForeground(new java.awt.Color(255, 255, 255));
        optd.setText("Driver");
        optd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(optu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(optd)
                .addGap(79, 79, 79))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optu)
                    .addComponent(optd))
                .addContainerGap())
        );

        jSeparator1.setBackground(new java.awt.Color(2, 154, 153));
        jSeparator1.setForeground(new java.awt.Color(2, 154, 153));

        jSeparator2.setBackground(new java.awt.Color(2, 154, 153));
        jSeparator2.setForeground(new java.awt.Color(2, 154, 153));

        jSeparator3.setBackground(new java.awt.Color(2, 154, 153));
        jSeparator3.setForeground(new java.awt.Color(2, 154, 153));

        jSeparator5.setBackground(new java.awt.Color(2, 154, 153));
        jSeparator5.setForeground(new java.awt.Color(2, 154, 153));

        jSeparator6.setBackground(new java.awt.Color(2, 154, 153));
        jSeparator6.setForeground(new java.awt.Color(2, 154, 153));

        jSeparator7.setBackground(new java.awt.Color(2, 154, 153));

        jSeparator8.setBackground(new java.awt.Color(2, 154, 153));

        Cancel.setBackground(new java.awt.Color(2, 154, 153));
        Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 154, 153)));

        CANCEL.setBackground(new java.awt.Color(37, 36, 36));
        CANCEL.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        CANCEL.setForeground(new java.awt.Color(255, 255, 255));
        CANCEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CANCEL.setText("C a n c e l");
        CANCEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CANCELMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CANCELMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CANCELMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CancelLayout = new javax.swing.GroupLayout(Cancel);
        Cancel.setLayout(CancelLayout);
        CancelLayout.setHorizontalGroup(
            CancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        CancelLayout.setVerticalGroup(
            CancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CancelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Clear.setBackground(new java.awt.Color(2, 154, 153));
        Clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 154, 153)));

        CLEAR.setBackground(new java.awt.Color(37, 36, 36));
        CLEAR.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        CLEAR.setForeground(new java.awt.Color(255, 255, 255));
        CLEAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CLEAR.setText("C l e a r");
        CLEAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLEARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CLEARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CLEARMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ClearLayout = new javax.swing.GroupLayout(Clear);
        Clear.setLayout(ClearLayout);
        ClearLayout.setHorizontalGroup(
            ClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClearLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ClearLayout.setVerticalGroup(
            ClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClearLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Confirm.setBackground(new java.awt.Color(2, 154, 153));
        Confirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 154, 153)));

        CONFIRM.setBackground(new java.awt.Color(37, 36, 36));
        CONFIRM.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        CONFIRM.setForeground(new java.awt.Color(255, 255, 255));
        CONFIRM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CONFIRM.setText("C o n f i r m");
        CONFIRM.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CONFIRMMouseDragged(evt);
            }
        });
        CONFIRM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CONFIRMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CONFIRMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CONFIRMMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CONFIRMMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ConfirmLayout = new javax.swing.GroupLayout(Confirm);
        Confirm.setLayout(ConfirmLayout);
        ConfirmLayout.setHorizontalGroup(
            ConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CONFIRM, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        ConfirmLayout.setVerticalGroup(
            ConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CONFIRM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        note.setBackground(new java.awt.Color(0, 0, 0));
        note.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        note.setForeground(new java.awt.Color(255, 255, 255));
        note.setText("Only need to be filled if you are registaring as a driver...");

        car.setBackground(new java.awt.Color(0, 0, 0));
        car.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        car.setForeground(new java.awt.Color(255, 255, 255));
        car.setText("Car");

        jSeparator10.setBackground(new java.awt.Color(2, 154, 153));

        reg_car.setBackground(new java.awt.Color(37, 36, 36));
        reg_car.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        reg_car.setForeground(new java.awt.Color(255, 255, 255));
        reg_car.setText("Not yet Registered your car. Click here....");
        reg_car.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reg_carMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reg_carMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reg_carMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(F_name, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                        .addComponent(L_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Email))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtF_name, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                            .addComponent(jSeparator1)
                                            .addComponent(txtL_name)
                                            .addComponent(jSeparator2)
                                            .addComponent(txtemail)
                                            .addComponent(jSeparator3))
                                        .addGap(141, 141, 141)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RE_pass)
                                            .addComponent(PASS, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(password2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(reg_car, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(212, 212, 212))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pan)
                                    .addComponent(Invite))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator8)
                                    .addComponent(jSeparator7)
                                    .addComponent(txtpan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtinvite, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(car)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(116, 116, 116)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(City)
                            .addComponent(Gender))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(optmale)
                                .addGap(18, 18, 18)
                                .addComponent(optfemale))
                            .addComponent(cmdcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(note, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(F_name)
                            .addComponent(txtF_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PASS))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_name)
                    .addComponent(txtL_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RE_pass)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Email)))
                .addGap(14, 14, 14)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(note)
                        .addGap(0, 48, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pan)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Gender)
                            .addComponent(optmale)
                            .addComponent(optfemale))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Invite)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(txtcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(car, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtinvite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmdcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(City)))
                        .addGap(83, 83, 83)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Confirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(reg_car)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CONFIRMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONFIRMMouseExited

        
        Confirm.setBorder(new LineBorder(Color.WHITE, 0, false));
    }//GEN-LAST:event_CONFIRMMouseExited
     
    
    
    
    
    
    private void CONFIRMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONFIRMMouseEntered

        
        Confirm.setBorder(new LineBorder(new Color(255,255,255) , 1 ,true));

    }//GEN-LAST:event_CONFIRMMouseEntered

    private void CONFIRMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONFIRMMouseClicked

        String cate ;
        String gen ;
        String car ;
        String inv ;
        String pan ;

        String city;
        String pwd1;
        String pwd2;
        String fn;
        String em;
        String ln;
        int I = 0;
        int i = I++;
        
        

        
        fn = txtF_name.getText();
        ln = txtL_name.getText();
        
        car = txtcar.getText();
        em = txtemail.getText();
        inv = txtinvite.getText();
        pan = txtpan.getText();
        
        pwd1 = password1.getText();
        pwd2 = password2.getText();
        city = cmdcity.getSelectedItem().toString();
        
        if(optu.isSelected())
         city="_";
        
        else if(optd.isSelected())
         city = cmdcity.getSelectedItem().toString();
        
        if(optu.isSelected())
         inv ="_";

        else if(optd.isSelected())
         inv = txtinvite.getText();
       
        if(optu.isSelected())
         pan = txtpan.getText();

        else if(optd.isSelected())
         cate = "Driver";


        if(optmale.isSelected())
         gen= "Male";
        else if(optfemale.isSelected())
         gen= "Female";

        else
         gen = "_";

        if(optu.isSelected())
        cate = "User";

        else if(optd.isSelected())
        cate = "Driver";
        
        else
        cate = "_";
        
    
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/car_bookings","root","mysql");
            Statement stmt = con.createStatement();
            String sq2 = ("insert into account_reg values('"+i+"','"+fn+"','"+ln+"','"+pwd1+"','"+em+"','"+gen+"','"+pan+"','"+inv+"','"+city+"','"+cate+"','"+car+"');");

            stmt.executeUpdate(sq2);

            if(!pwd1.equals(pwd2)){
            
                JOptionPane.showMessageDialog(null, "Password Do not Match");
            }
            
            else 
            {
                JOptionPane.showMessageDialog(null,"done");
            }
            
           
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

    }//GEN-LAST:event_CONFIRMMouseClicked
    }
    private void CLEARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLEARMouseExited
        
        Clear.setBorder(new LineBorder(Color.WHITE, 0, false));
    }//GEN-LAST:event_CLEARMouseExited

    private void CLEARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLEARMouseEntered
       
        Clear.setBorder(new LineBorder(new Color(255,255,255), 1, true));
    }//GEN-LAST:event_CLEARMouseEntered

    private void CLEARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLEARMouseClicked
        // TODO add your handling code here:
        txtF_name.setText("");
        txtemail.setText("");
        txtL_name.setText("");
        
        password2.setText("");
        password1.setText("");
        txtpan.setText("");
        
        txtinvite.setText("");
        txtcar.setText("");
        
    }//GEN-LAST:event_CLEARMouseClicked

    private void CANCELMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELMouseExited
        
      
        Cancel.setBorder(new LineBorder(Color.WHITE, 0, false));
    }//GEN-LAST:event_CANCELMouseExited

    private void CANCELMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELMouseEntered
       
        Cancel.setBorder(new LineBorder(new Color(255, 255, 255), 1, true));
    }//GEN-LAST:event_CANCELMouseEntered

    private void CANCELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANCELMouseClicked
        
        this.setVisible(false);
        new login().setVisible(true);

    }//GEN-LAST:event_CANCELMouseClicked

    private void optdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optdActionPerformed

        if(optd.isSelected())
        {
            txtpan.setEditable(true);
           
            cmdcity.setEnabled(true);
            txtinvite.setEditable(true);
            txtpan.setEditable(true);
            
            txtcar.setEditable(true);
            optmale.setEnabled(true);

        }
        if (txtF_name.equals("") || txtL_name.equals("") || password1.equals("") || txtemail.equals("")  || password2.equals("") || car.equals("") || txtinvite.equals("") || txtpan.equals("") )
        {
            JOptionPane.showMessageDialog(null, "empty fields");
        }
    }//GEN-LAST:event_optdActionPerformed

    private void optuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optuActionPerformed

        if(optu.isSelected())
        {
            txtpan.setEditable(false);
            
            cmdcity.setEnabled(false);
            txtinvite.setEditable(false);
            txtpan.setEditable(false);
            
            txtcar.setEditable(false);
            optmale.setEnabled(false);
        }

        if (txtF_name.equals("") || txtL_name.equals("") || password1.equals("") || txtemail.equals("")  || password2.equals("") )
        {
            JOptionPane.showMessageDialog(null, "empty fields");
        }

    }//GEN-LAST:event_optuActionPerformed

    private void optfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optfemaleActionPerformed

    }//GEN-LAST:event_optfemaleActionPerformed

    private void optmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optmaleActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_optmaleActionPerformed

    private void txtinviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinviteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinviteActionPerformed

    private void password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password2ActionPerformed
     
    }//GEN-LAST:event_password2ActionPerformed

    private void reg_carMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_carMouseClicked
        
        this.setVisible(false);
        new Car_reg().setVisible(true);
         
    }//GEN-LAST:event_reg_carMouseClicked

    private void reg_carMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_carMouseEntered
        reg_car.setForeground(Color.WHITE);
    }//GEN-LAST:event_reg_carMouseEntered

    private void reg_carMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_carMouseExited

    }//GEN-LAST:event_reg_carMouseExited

    private void CONFIRMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONFIRMMousePressed
        
    }//GEN-LAST:event_CONFIRMMousePressed

    private void CONFIRMMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONFIRMMouseDragged
      
    }//GEN-LAST:event_CONFIRMMouseDragged
private int xMouse , yMouse;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
         xMouse = evt.getX();
       yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x-xMouse, y- yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    
    
        
    
    public boolean pass(){
         String pwd1 = password1.getText();
          String pwd2 = password2.getText();
              if (pwd1.equals(pwd2)) 
            {
                JOptionPane.showMessageDialog(null, "Password doesn't Match");
            }
         return false;
              
    }
 
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create_acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create_acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create_acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create_acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create_acc().setVisible(true);
            }
        });}
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BTMgen;
    private javax.swing.ButtonGroup BTMud;
    private javax.swing.JLabel CANCEL;
    private javax.swing.JLabel CLEAR;
    private javax.swing.JLabel CONFIRM;
    private javax.swing.JPanel Cancel;
    private javax.swing.JLabel City;
    private javax.swing.JPanel Clear;
    private javax.swing.JPanel Confirm;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel F_name;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel Invite;
    private javax.swing.JLabel L_name;
    private javax.swing.JLabel PASS;
    private javax.swing.JLabel Pan;
    private javax.swing.JLabel RE_pass;
    private javax.swing.JLabel car;
    private javax.swing.JComboBox<String> cmdcity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel note;
    private javax.swing.JRadioButton optd;
    private javax.swing.JRadioButton optfemale;
    private javax.swing.JRadioButton optmale;
    private javax.swing.JRadioButton optu;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    private javax.swing.JLabel reg_car;
    private javax.swing.JTextField txtF_name;
    private javax.swing.JTextField txtL_name;
    private javax.swing.JTextField txtcar;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtinvite;
    private javax.swing.JTextField txtpan;
    // End of variables declaration//GEN-END:variables

}
