
import java.awt.Color;
import javax.swing.border.LineBorder;

import java.sql.Connection;
import java.sql.DriverManager;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;




public class login extends javax.swing.JFrame {

    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setOpacity(0.9f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        cancelpanel = new javax.swing.JPanel();
        cancellabel = new javax.swing.JLabel();
        signinpanel = new javax.swing.JPanel();
        signinlabel = new javax.swing.JLabel();
        clear_panel = new javax.swing.JPanel();
        clear = new javax.swing.JLabel();
        New_acc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(29, 59, 85));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 59, 85), 6));

        header.setBackground(new java.awt.Color(29, 59, 85));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user (14).png"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name");

        Username.setBackground(new java.awt.Color(29, 59, 85));
        Username.setForeground(new java.awt.Color(2, 154, 153));
        Username.setBorder(null);
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(2, 154, 153));
        jSeparator1.setForeground(new java.awt.Color(2, 154, 153));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        Password.setBackground(new java.awt.Color(29, 59, 85));
        Password.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(2, 154, 153));
        Password.setBorder(null);
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(2, 154, 153));
        jSeparator2.setForeground(new java.awt.Color(2, 154, 153));

        cancelpanel.setBackground(new java.awt.Color(2, 154, 153));
        cancelpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cancellabel.setBackground(new java.awt.Color(53, 69, 95));
        cancellabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cancellabel.setForeground(new java.awt.Color(255, 255, 255));
        cancellabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancellabel.setText("C a n c e l");
        cancellabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancellabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancellabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancellabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout cancelpanelLayout = new javax.swing.GroupLayout(cancelpanel);
        cancelpanel.setLayout(cancelpanelLayout);
        cancelpanelLayout.setHorizontalGroup(
            cancelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancellabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        cancelpanelLayout.setVerticalGroup(
            cancelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancellabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        signinpanel.setBackground(new java.awt.Color(2, 154, 153));
        signinpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        signinlabel.setBackground(new java.awt.Color(53, 69, 95));
        signinlabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        signinlabel.setForeground(new java.awt.Color(255, 255, 255));
        signinlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signinlabel.setText("S i g n   I n");
        signinlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signinlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signinlabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout signinpanelLayout = new javax.swing.GroupLayout(signinpanel);
        signinpanel.setLayout(signinpanelLayout);
        signinpanelLayout.setHorizontalGroup(
            signinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signinlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        signinpanelLayout.setVerticalGroup(
            signinpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signinlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        clear_panel.setBackground(new java.awt.Color(2, 154, 153));

        clear.setBackground(new java.awt.Color(53, 69, 95));
        clear.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clear.setText("C l e a r");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });

        javax.swing.GroupLayout clear_panelLayout = new javax.swing.GroupLayout(clear_panel);
        clear_panel.setLayout(clear_panelLayout);
        clear_panelLayout.setHorizontalGroup(
            clear_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clear_panelLayout.createSequentialGroup()
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        clear_panelLayout.setVerticalGroup(
            clear_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        New_acc.setBackground(new java.awt.Color(0, 0, 0));
        New_acc.setForeground(new java.awt.Color(255, 255, 255));
        New_acc.setText("Don't have an account. Click here!!!!.....");
        New_acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                New_accMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                New_accMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                New_accMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(New_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGap(47, 47, 47)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Username)
                                        .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                        .addComponent(jSeparator2))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cancelpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(clear_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(signinpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(49, Short.MAX_VALUE))))
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 42, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signinpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(New_acc)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        
    }//GEN-LAST:event_UsernameActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        
    }//GEN-LAST:event_PasswordActionPerformed

    private void cancellabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancellabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cancellabelMouseClicked

    private void cancellabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancellabelMouseEntered
       
       cancelpanel.setBorder(new LineBorder(new Color(255,255,255) , 1 ,true));
    }//GEN-LAST:event_cancellabelMouseEntered

    private void cancellabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancellabelMouseExited
        
       cancelpanel.setBorder(new LineBorder(new Color(2,154,153) , 0 ,false));
    }//GEN-LAST:event_cancellabelMouseExited

    private void signinlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinlabelMouseClicked
       
        

       
        
       Connection conn=null;
       Statement stmt=null;
   
       String nm=Username.getText();
       String pwd= new String(Password.getPassword());
       if (nm.equals("admin"))
       {  if (pwd.equals("password"))
       {new Admin().setVisible(true);
           this.setVisible(false);
           System.out.println("check admin");
       }
       }else {
    System.out.println("not admin");
   Connection conn1=null;
   Statement stmt1=null;
       
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/car_bookings","root","mysql");
            Statement stmt2 = con.createStatement();
            String sql = ("select * from account_reg where F_name = '"+nm+"';");
            
             
           ResultSet rs = stmt2.executeQuery(sql);
           
            if(!rs.isBeforeFirst())
       {
        JOptionPane.showMessageDialog(null,"naaaaa");
       }
       else
       {
           String pass;
           rs.next();
           pass=rs.getString("Password");
           if(pwd.equalsIgnoreCase(pass))
           {
            System.out.print("weqwkjcqhbc");
            new Home1().setVisible(true);
            this.setVisible(false);
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Incorrect Password");
           }
       }
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,e.getMessage());

        }
       }
    }//GEN-LAST:event_signinlabelMouseClicked

    private void signinlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinlabelMouseEntered
        
       signinpanel.setBorder(new LineBorder(new Color(255,255,255) , 1 ,true));
    }//GEN-LAST:event_signinlabelMouseEntered

    private void signinlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinlabelMouseExited
          
       signinpanel.setBorder(new LineBorder(new Color(2,154,153) , 0 ,false));
    }//GEN-LAST:event_signinlabelMouseExited
private int xMouse , yMouse;
    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
       xMouse = evt.getX();
       yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x-xMouse, y- yMouse);
        
    }//GEN-LAST:event_headerMouseDragged

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        
        Username.setText("");
        Password.setText("");
    }//GEN-LAST:event_clearMouseClicked

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        
       
       clear_panel.setBorder(new LineBorder(new Color(255,255,255) , 1 ,true));
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        
       
       clear_panel.setBorder(new LineBorder(new Color(2,154,153) , 0 ,false));
    }//GEN-LAST:event_clearMouseExited

    private void New_accMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_accMouseClicked
       
        this.setVisible(false);
       new create_acc().setVisible(true);
    }//GEN-LAST:event_New_accMouseClicked

    private void New_accMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_accMouseEntered
        
        New_acc.setForeground(Color.WHITE);
    
    }//GEN-LAST:event_New_accMouseEntered

    private void New_accMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_accMouseExited
        
        
    }//GEN-LAST:event_New_accMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel New_acc;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel cancellabel;
    private javax.swing.JPanel cancelpanel;
    private javax.swing.JLabel clear;
    private javax.swing.JPanel clear_panel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel signinlabel;
    private javax.swing.JPanel signinpanel;
    // End of variables declaration//GEN-END:variables
}
