
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Amar
 */
public class Rent_car_1 extends javax.swing.JFrame {

    /**
     * Creates new form Rent_car_1
     */
    public Rent_car_1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setOpacity(0.9f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmpay = new javax.swing.ButtonGroup();
        btmgen = new javax.swing.ButtonGroup();
        logo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FDATE = new com.toedter.calendar.JDateChooser();
        TDATE = new com.toedter.calendar.JDateChooser();
        Licence = new javax.swing.JPanel();
        issue = new javax.swing.JLabel();
        ID = new com.toedter.calendar.JDateChooser();
        validity = new javax.swing.JLabel();
        VAL = new com.toedter.calendar.JDateChooser();
        dob = new javax.swing.JLabel();
        DOB = new com.toedter.calendar.JDateChooser();
        licenceno = new javax.swing.JLabel();
        gen = new javax.swing.JLabel();
        optm = new javax.swing.JRadioButton();
        optf = new javax.swing.JRadioButton();
        txtl = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        confirm = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtcode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cash = new javax.swing.JRadioButton();
        online = new javax.swing.JRadioButton();
        card = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        logo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lease.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel3.setText("Car Rental");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel2)
                .addGroup(logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addContainerGap())))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(50, 50, 50))))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("From Date");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Till Date");

        FDATE.setBackground(new java.awt.Color(255, 255, 255));
        FDATE.setDateFormatString("yyyy-MM-dd");

        TDATE.setBackground(new java.awt.Color(255, 255, 255));
        TDATE.setDateFormatString("yyyy-MM-dd");

        Licence.setBackground(new java.awt.Color(255, 255, 255));
        Licence.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Driving Licence", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24))); // NOI18N

        issue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        issue.setText("Issue Date");

        ID.setBackground(new java.awt.Color(255, 255, 255));
        ID.setDateFormatString("yyyy-MM-dd");

        validity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        validity.setText("Validity");

        VAL.setBackground(new java.awt.Color(255, 255, 255));
        VAL.setDateFormatString("yyyy-MM-dd");

        dob.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dob.setText("Date of Birth");

        DOB.setBackground(new java.awt.Color(255, 255, 255));
        DOB.setDateFormatString("yyyy-MM-dd");

        licenceno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        licenceno.setText("Licence Number");

        gen.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        gen.setText("Gender");

        optm.setBackground(new java.awt.Color(255, 255, 255));
        btmgen.add(optm);
        optm.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        optm.setText("Male");

        optf.setBackground(new java.awt.Color(255, 255, 255));
        btmgen.add(optf);
        optf.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        optf.setText("Female");

        txtl.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtl.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout LicenceLayout = new javax.swing.GroupLayout(Licence);
        Licence.setLayout(LicenceLayout);
        LicenceLayout.setHorizontalGroup(
            LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LicenceLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LicenceLayout.createSequentialGroup()
                        .addComponent(licenceno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(272, 272, 272)
                        .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dob)
                            .addComponent(validity))
                        .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LicenceLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LicenceLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(VAL, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LicenceLayout.createSequentialGroup()
                        .addComponent(issue, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LicenceLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(gen, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(optm, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(optf))
                            .addGroup(LicenceLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtl)
                                        .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(86, 86, 86))
        );
        LicenceLayout.setVerticalGroup(
            LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LicenceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LicenceLayout.createSequentialGroup()
                        .addComponent(licenceno)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LicenceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dob, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LicenceLayout.createSequentialGroup()
                                .addComponent(txtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30)
                .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(validity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(issue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(LicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optm)
                    .addComponent(optf)
                    .addComponent(gen))
                .addGap(25, 25, 25))
        );

        confirm.setBackground(new java.awt.Color(255, 255, 255));
        confirm.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        confirm.setText("C o n f i r m");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        clear.setText("C l e a r");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Car Code");

        txtcode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("select car...");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setText("Payment");

        btmpay.add(cash);
        cash.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cash.setText("Cash");

        btmpay.add(online);
        online.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        online.setText("Online");

        btmpay.add(card);
        card.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        card.setText("Card");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Licence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel6)))
                .addGap(32, 32, 32)
                .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(confirm))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(218, 218, 218))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addGap(109, 109, 109)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(FDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(63, 63, 63)
                        .addComponent(TDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(60, 60, 60)
                        .addComponent(cash)
                        .addGap(40, 40, 40)
                        .addComponent(online)
                        .addGap(49, 49, 49)
                        .addComponent(card)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(FDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cash)
                    .addComponent(online)
                    .addComponent(card))
                .addGap(18, 18, 18)
                .addComponent(Licence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        
       String fdate = ((JTextField)FDATE.getDateEditor().getUiComponent()).getText();
       String tdate = ((JTextField)TDATE.getDateEditor().getUiComponent()).getText();
       String dob = ((JTextField)DOB.getDateEditor().getUiComponent()).getText();
       String id = ((JTextField)ID.getDateEditor().getUiComponent()).getText();
       String val = ((JTextField)VAL.getDateEditor().getUiComponent()).getText();
        String code = txtcode.getText();
        String gen;
        String pay;
        String ln = txtl.getText();
        int I = 0;
       int i =I++;
        String bo = "booked";
        String av = "available";
        int cost = 0; 
        
        
         
        if(optm.isSelected())
            gen= "Male";
        else if(optf.isSelected())
            gen= "Female";
        else
            gen="Male";
        
        
        if(cash.isSelected())
            pay = "Cash";
        else if(card.isSelected())
            pay = "Card";
        else if (online.isSelected())
            pay ="Online";
        else 
            pay="Cash";
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/car_bookings","root","mysql");
            Statement stmt = con.createStatement();
            String sq2 = ("insert into rent_details values('"+i+"','"+fdate+"','"+tdate+"','"+ln+"','"+gen+"','"+dob+"','"+id+"','"+val+"','"+pay+"','"+code+"','"+cost+"');");
            String sq3 = ("update car_details set Status ='"+bo+"' where Car_code ='"+code+"' and Status = '"+av+"';");
            String sq4 = ("update car_reg set Status ='"+bo+"' where Car_code ='"+code+"' and Status ='"+av+"';");
            stmt.executeUpdate(sq2);
            stmt.executeUpdate(sq3);
             stmt.executeUpdate(sq4);

            if (FDATE.equals("") || TDATE.equals("") || txtl.equals("") || DOB.equals("")  || VAL.equals("") || ID.equals("") || txtcode.equals("") )
            {
                JOptionPane.showMessageDialog(null, "empty fields");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Succesfully added");
                this.setVisible(false);
                new booked().setVisible(true);
            }

            } 
             catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

            }
    }//GEN-LAST:event_confirmActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        
        txtcode.setText("");
        txtl.setText("");
        ((JTextField)TDATE.getDateEditor().getUiComponent()).setText("");
        ((JTextField)FDATE.getDateEditor().getUiComponent()).setText("");
        ((JTextField)DOB.getDateEditor().getUiComponent()).setText("");
        ((JTextField)ID.getDateEditor().getUiComponent()).setText("");
        ((JTextField)VAL.getDateEditor().getUiComponent()).setText("");
        
        
        
    }//GEN-LAST:event_clearActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.setVisible(false);
        new Home1().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rent_car_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rent_car_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rent_car_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rent_car_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rent_car_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DOB;
    private com.toedter.calendar.JDateChooser FDATE;
    private com.toedter.calendar.JDateChooser ID;
    private javax.swing.JPanel Licence;
    private com.toedter.calendar.JDateChooser TDATE;
    private com.toedter.calendar.JDateChooser VAL;
    private javax.swing.ButtonGroup btmgen;
    private javax.swing.ButtonGroup btmpay;
    private javax.swing.JRadioButton card;
    private javax.swing.JRadioButton cash;
    private javax.swing.JButton clear;
    private javax.swing.JButton confirm;
    private javax.swing.JPanel content;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel gen;
    private javax.swing.JLabel issue;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel licenceno;
    private javax.swing.JPanel logo;
    private javax.swing.JRadioButton online;
    private javax.swing.JRadioButton optf;
    private javax.swing.JRadioButton optm;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtl;
    private javax.swing.JLabel validity;
    // End of variables declaration//GEN-END:variables
}
